syntax = "proto3";

package tunnelconfig;

import "google/protobuf/empty.proto";

option go_package = "github.com/mullvad/rsw-proto/tunnelconfig";

service TunnelConfig {
  rpc RegisterForNotificationsV1(RegisterForNotificationsRequestV1) returns (google.protobuf.Empty) {}
}

message RegisterForNotificationsRequestV1 {
  // Pubkey of the WireGuard peer enrolling to receive notifications.
  // This should be the same key as the one associated with the active tunnel
  // being used to deliver this request.
  bytes wg_pubkey = 1;
  // UDP port where the client is listening for notifications.
  // Valid range of values is 1-65535.
  // The relay will address the client on the source address used when sending this request.
  uint32 port = 2;
}
