// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: tunnelconfig/tunnelconfig.proto

package tunnelconfig

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterForNotificationsRequestV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pubkey of the WireGuard peer enrolling to receive notifications.
	// This should be the same key as the one associated with the active tunnel
	// being used to deliver this request.
	WgPubkey []byte `protobuf:"bytes,1,opt,name=wg_pubkey,json=wgPubkey,proto3" json:"wg_pubkey,omitempty"`
	// UDP port where the client is listening for notifications.
	// Valid range of values is 1-65535.
	// The relay will address the client on the source address used when sending this request.
	Port          uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterForNotificationsRequestV1) Reset() {
	*x = RegisterForNotificationsRequestV1{}
	mi := &file_tunnelconfig_tunnelconfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterForNotificationsRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterForNotificationsRequestV1) ProtoMessage() {}

func (x *RegisterForNotificationsRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_tunnelconfig_tunnelconfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterForNotificationsRequestV1.ProtoReflect.Descriptor instead.
func (*RegisterForNotificationsRequestV1) Descriptor() ([]byte, []int) {
	return file_tunnelconfig_tunnelconfig_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterForNotificationsRequestV1) GetWgPubkey() []byte {
	if x != nil {
		return x.WgPubkey
	}
	return nil
}

func (x *RegisterForNotificationsRequestV1) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_tunnelconfig_tunnelconfig_proto protoreflect.FileDescriptor

var file_tunnelconfig_tunnelconfig_proto_rawDesc = string([]byte{
	0x0a, 0x1f, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x74,
	0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x21,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56,
	0x31, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x67, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x77, 0x67, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x32, 0x77, 0x0a, 0x0c, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x67, 0x0a, 0x1a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x6f,
	0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x56, 0x31,
	0x12, 0x2f, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56,
	0x31, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x6c, 0x6c, 0x76, 0x61,
	0x64, 0x2f, 0x72, 0x73, 0x77, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_tunnelconfig_tunnelconfig_proto_rawDescOnce sync.Once
	file_tunnelconfig_tunnelconfig_proto_rawDescData []byte
)

func file_tunnelconfig_tunnelconfig_proto_rawDescGZIP() []byte {
	file_tunnelconfig_tunnelconfig_proto_rawDescOnce.Do(func() {
		file_tunnelconfig_tunnelconfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tunnelconfig_tunnelconfig_proto_rawDesc), len(file_tunnelconfig_tunnelconfig_proto_rawDesc)))
	})
	return file_tunnelconfig_tunnelconfig_proto_rawDescData
}

var file_tunnelconfig_tunnelconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tunnelconfig_tunnelconfig_proto_goTypes = []any{
	(*RegisterForNotificationsRequestV1)(nil), // 0: tunnelconfig.RegisterForNotificationsRequestV1
	(*emptypb.Empty)(nil),                     // 1: google.protobuf.Empty
}
var file_tunnelconfig_tunnelconfig_proto_depIdxs = []int32{
	0, // 0: tunnelconfig.TunnelConfig.RegisterForNotificationsV1:input_type -> tunnelconfig.RegisterForNotificationsRequestV1
	1, // 1: tunnelconfig.TunnelConfig.RegisterForNotificationsV1:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tunnelconfig_tunnelconfig_proto_init() }
func file_tunnelconfig_tunnelconfig_proto_init() {
	if File_tunnelconfig_tunnelconfig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tunnelconfig_tunnelconfig_proto_rawDesc), len(file_tunnelconfig_tunnelconfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tunnelconfig_tunnelconfig_proto_goTypes,
		DependencyIndexes: file_tunnelconfig_tunnelconfig_proto_depIdxs,
		MessageInfos:      file_tunnelconfig_tunnelconfig_proto_msgTypes,
	}.Build()
	File_tunnelconfig_tunnelconfig_proto = out.File
	file_tunnelconfig_tunnelconfig_proto_goTypes = nil
	file_tunnelconfig_tunnelconfig_proto_depIdxs = nil
}
