// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: tunnelconfig/tunnelconfig.proto

package tunnelconfig

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TunnelConfig_RegisterForNotificationsV1_FullMethodName = "/tunnelconfig.TunnelConfig/RegisterForNotificationsV1"
)

// TunnelConfigClient is the client API for TunnelConfig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TunnelConfigClient interface {
	RegisterForNotificationsV1(ctx context.Context, in *RegisterForNotificationsRequestV1, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type tunnelConfigClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelConfigClient(cc grpc.ClientConnInterface) TunnelConfigClient {
	return &tunnelConfigClient{cc}
}

func (c *tunnelConfigClient) RegisterForNotificationsV1(ctx context.Context, in *RegisterForNotificationsRequestV1, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TunnelConfig_RegisterForNotificationsV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TunnelConfigServer is the server API for TunnelConfig service.
// All implementations must embed UnimplementedTunnelConfigServer
// for forward compatibility.
type TunnelConfigServer interface {
	RegisterForNotificationsV1(context.Context, *RegisterForNotificationsRequestV1) (*emptypb.Empty, error)
	mustEmbedUnimplementedTunnelConfigServer()
}

// UnimplementedTunnelConfigServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTunnelConfigServer struct{}

func (UnimplementedTunnelConfigServer) RegisterForNotificationsV1(context.Context, *RegisterForNotificationsRequestV1) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterForNotificationsV1 not implemented")
}
func (UnimplementedTunnelConfigServer) mustEmbedUnimplementedTunnelConfigServer() {}
func (UnimplementedTunnelConfigServer) testEmbeddedByValue()                      {}

// UnsafeTunnelConfigServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelConfigServer will
// result in compilation errors.
type UnsafeTunnelConfigServer interface {
	mustEmbedUnimplementedTunnelConfigServer()
}

func RegisterTunnelConfigServer(s grpc.ServiceRegistrar, srv TunnelConfigServer) {
	// If the following call pancis, it indicates UnimplementedTunnelConfigServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TunnelConfig_ServiceDesc, srv)
}

func _TunnelConfig_RegisterForNotificationsV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterForNotificationsRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelConfigServer).RegisterForNotificationsV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelConfig_RegisterForNotificationsV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelConfigServer).RegisterForNotificationsV1(ctx, req.(*RegisterForNotificationsRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

// TunnelConfig_ServiceDesc is the grpc.ServiceDesc for TunnelConfig service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnelConfig_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnelconfig.TunnelConfig",
	HandlerType: (*TunnelConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterForNotificationsV1",
			Handler:    _TunnelConfig_RegisterForNotificationsV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tunnelconfig/tunnelconfig.proto",
}
